library(shiny)
library(DT)
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(dplyr)
library(spatstat)
library(shinydashboard)
options(shiny.maxRequestSize = 30*1024^2)
library(dashboardthemes)
library(plotly)
library(pheatmap)
#library(RColorBrewer)
#library(vioplot)
library(ggfortify)